
export const data = [
    {
        title: 'Alkybank (Alkemy)',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708051/Portafolio/AlkyBank/1_ffhpiu.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708051/Portafolio/AlkyBank/2_ukyk3p.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708051/Portafolio/AlkyBank/3_nnfewd.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/4_nusgzo.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/5_tab3rn.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/6_fmnm55.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/7_s0baqz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708053/Portafolio/AlkyBank/8_uq8qg9.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/9_w42iua.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1668708052/Portafolio/AlkyBank/10_a0rq7h.jpg',
        ],
        description: {
            items: [
                'Billetera virtual para un banco.',
                'Proyecto realizado durante la aceleración de alkemy.',
                'Realizado en equipo usando metodologías agiles.',
                'Diseño responsive.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/SkillUp-Grupo5/SKU-5",
        demo: "https://alkybank-wallet.netlify.app/",
    },
    {
        title: 'Dashboard App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/1_pak7lt.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/2_ayd78b.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/3_uaycto.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/4_lwkshc.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/5_nt90ea.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/6_b3pji1.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/7_jfxixz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149687/Portafolio/DashboardApp/8_gyhofb.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/9_vh0yv3.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/10_yfgifp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/11_letzr4.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/12_ncnfrj.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/13_mmjo20.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149688/Portafolio/DashboardApp/14_p6e0rd.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/15_nwwubh.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/16_vybzvz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/17_adzzoy.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/18_wwx9xz.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149689/Portafolio/DashboardApp/19_zh91bu.jpg',
        ],
        description: {
            items: [
                'Dashboard de un proyecto eccomerce en proceso.',
                'Proyecto realizado por mi cuenta tanto front como back.',
                'Dos roles permitidos: Moderador y Administrador.',
                'Cuenta con un sistema de registros.',
                'Diseño responsive.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: true,
            express: true,
            mongoDb: true,
        },
        github: "https://github.com/lucasgojeda/eccomerce-app-dashboard",
        demo: "https://my-eccomerce-dashboard.netlify.app/",
    },
    {
        title: 'Calendar App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/1_lcywo9.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/2_dc4yrb.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/3_pfnvqr.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/4_vt3d9v.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/5_ftfkpi.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149645/Portafolio/CalendarApp/6_w2gyib.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149646/Portafolio/CalendarApp/7_ktv6kx.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149646/Portafolio/CalendarApp/8_bhmnjl.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149646/Portafolio/CalendarApp/9_m2cz8b.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1662149646/Portafolio/CalendarApp/10_k5mxy0.jpg',
        ],
        description: {
            items: [
                'Aplicación de calendario para agendar citas.',
                'Proyecto realizado en el curso de fernando herrera.',
                'Incluye pruebas unitarias.',
                'Diseño responsive.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: true,
            express: true,
            mongoDb: true,
        },
        github: "https://github.com/lucasgojeda/front-calendar-app-vite",
        demo: "https://calendar-app2.herokuapp.com/",
    },
    {
        title: 'Journal App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/2_f2qdlp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/3_oipal5.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/4_n7j2ky.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/5_mlm8gp.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976642/Portafolio/JournalApp/1_hxvqfl.jpg',
        ],
        description: {
            items: [
                'Aplicación notas.',
                'Proyecto realizado en el curso de fernando herrera.',
                'Incluye pruebas unitarias.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/journal-app-vite",
        demo: "https://my-journal-app-vite.netlify.app/",
    },
    {
        title: 'Heroes App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975970/Portafolio/HeroesApp/4_qurxyy.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975971/Portafolio/HeroesApp/1_wg4eoo.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975971/Portafolio/HeroesApp/2_f8g2sq.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975971/Portafolio/HeroesApp/9_mtz4fr.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975971/Portafolio/HeroesApp/3_pq6y2n.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975970/Portafolio/HeroesApp/5_dzziya.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975970/Portafolio/HeroesApp/6_yktmxg.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975971/Portafolio/HeroesApp/10_b7goe9.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975970/Portafolio/HeroesApp/7_nbwe9u.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975970/Portafolio/HeroesApp/8_ofkrms.jpg',
        ],
        description: {
            items: [
                'Aplicación de heroes.',
                'En ella encontramos información e imagenes de los heroes.',
                'Proyecto realizado en el curso de fernando herrera.',
                'Incluye pruebas unitarias.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/heroes-app-vite",
        demo: "https://my-heroes-app.netlify.app/",
    },
    {
        title: 'Gif Expert App',
        img: [
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/1_t7fyyw.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/2_ym4o47.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661976307/Portafolio/GifExpertApp/5_rksyqb.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/5_cf0rax.jpg',
            'https://res.cloudinary.com/the-kings-company/image/upload/v1661975717/Portafolio/GifExpertApp/4_vd6nqf.jpg',
        ],
        description: {
            items: [
                'Buscador de gifs consumidos desde una API pública.',
                'Proyecto realizado en el curso de fernando herrera.',
                'Incluye pruebas unitarias.',
                'Para más detalles ir al repositorio de github.',
            ]
        },
        tecnologias: {
            html: true,
            css: true,
            sass: false,
            react: true,
            javascript: true,
            node: false,
            express: false,
            mongoDb: false,
        },
        github: "https://github.com/lucasgojeda/git-expert-app-vite",
        demo: "https://my-gif-expert-app.netlify.app/",
    },
]